#!/bin/bash
# some stuff we don't care about really.
cp -v ../conf/piotr.kuczynski\@gmail.com.pgp ../conf/mpapis\@gmail.com.pgp $final_path
chown $app:$app $final_path/piotr.kuczynski\@gmail.com.pgp $final_path/mpapis\@gmail.com.pgp
sudo -u $app gpg --import $final_path/piotr.kuczynski\@gmail.com.pgp $final_path/mpapis\@gmail.com.pgp
pushd $final_path
sudo -u $app curl -sSL https://get.rvm.io | sudo -u $app bash -s stable
sudo -u $app $final_path/.rvm/bin/rvm autolibs read-fail
# avoid some issues where /tmp is not big enough
export TMPDIR=$final_path/.gcc_tmp
sudo -u $app mkdir -p $TMPDIR
# unfortunately no prebuilt for debian... this will be long
should_display_rvm_log=1
sudo -u $app TMPDIR=$TMPDIR $final_path/.rvm/bin/rvm install 2.4 
should_display_rvm_log=0
popd

