#!/bin/bash
# some stuff we don't care about really.
# clone ynh_experimental helpers
pushd $final_path
if [ -x Experimental_helpers ]; then
  pushd Experimental_helpers
  ynh_exec_warn_less git fetch
  popd
else
  ynh_exec_warn_less git clone https://github.com/YunoHost-Apps/Experimental_helpers.git
fi
pushd Experimental_helpers
ynh_exec_warn_less git checkout d05b4db
source ./ynh_install_ruby/ynh_install_ruby
popd
popd
ynh_exec_warn_less ynh_install_ruby --ruby_version=2.6.6

