#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get --app $app --key domain)
admin=$(ynh_app_setting_get --app $app --key admin)
final_path=$(ynh_app_setting_get --app $app --key final_path)

ynh_abort_if_errors

upgrade_type=$(ynh_check_app_version_changed)
# nothing to do yet!!
if [ "$upgrade_type" == "UPGRADE_APP" ]
then
  # do something!
  echo "to be implemented"
fi
